services:
  backend:
    build:
      context: ./backend
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
